export const projects = [
  {
    name: 'Password Generator',
    description: 'Generate a random password with specific user settings',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/password-generator',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/password-generator',
  },
  {
    name: 'Auto Text Effect',
    description:
      'Web component with feature typing effect. Control speed using input field or keyboard arrows.',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/auto-text-effect',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/auto-text-effect',
  },

  {
    name: 'Hearts Click',
    description: 'Generate hearts at double-click events',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/double-heart-click',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/double-heart-click',
  },
  {
    name: 'Search Profiles',
    description: 'Search for any GitHub profile and returns key information.  Uses the GitHub API.',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/github-profiles',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/github-profiles',
  },
  {
    name: 'Toast Notifications',
    description: 'Generate toast notifications',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/toast-notifications',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/toast-notifications',
  },
  {
    name: 'Vertical Slider',
    description: 'Image carousel with sliding double vertical panels',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/double-vertical-slider',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/double-vertical-slider',
  },
  {
    name: 'Sticky Navigation',
    description: 'Website template with feature sticky navigation',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/sticky-navigation',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/sticky-navigation',
  },
  {
    name: 'Content Placeholder',
    description: 'Content placeholder component',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/content-placeholder',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/content-placeholder',
  },
  {
    name: 'Kinetic Loader',
    description: 'Kinetic page loading component',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/kinetic-loader',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/kinetic-loader',
  },
  {
    name: 'Drawing App',
    description: 'Drawing app using HTML canvas',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/drawing-app',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/drawing-app',
  },
  {
    name: "Drag 'N' Drop",
    description: 'Drag and drop component',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/drag-n-drop',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/drag-n-drop',
  },
  {
    name: 'Button Ripple',
    description: 'Button ripple effect',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/button-ripple',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/button-ripple',
  },
  {
    name: 'Theme Clock',
    description: 'Theme clock with feature dark mode toggle',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/theme-clock',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/theme-clock',
  },
  {
    name: 'Background Slider',
    description: 'Background slider project',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/background-slider',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/background-slider',
  },

  {
    name: 'Movie App',
    description: 'Search for movies and view movie info and ratings. Uses the moviedb API',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/movie-app',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/movie-app',
  },
  {
    name: 'Drink Water',
    description: 'Track your water intake with this handy water tracking app',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/drink-water',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/drink-water',
  },
  {
    name: 'Incrementing Counter',
    description: 'Incrementing counter widget',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/incrementing-counter',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/incrementing-counter',
  },
  {
    name: 'Animated Navigation',
    description: 'Website template with feature animated expanding navigation',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/animated-navigation',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/animated-navigation',
  },
  {
    name: 'Random Picker',
    description: 'Enter all of the choices divided by commas. Then press enter when you are done.',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/random-choice-picker',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/random-choice-picker',
  },
  {
    name: 'FAQ Collapse',
    description: 'Frequently asked questions',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/faq-collapse',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/faq-collapse',
  },
  {
    name: 'Event Keycodes',
    description: 'Press any key to get the keycode',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/event-keycodes',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/event-keycodes',
  },
  {
    name: 'Dad Jokes',
    description: 'Dad style programming jokes and more; these jokes only work if you git them',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/dad-jokes/index',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/dad-jokes',
  },
  {
    name: 'Sound Board',
    description: 'Handy sound effects board',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/sound-board',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/sound-board',
  },
  {
    name: 'Form Wave',
    description: 'Login form with feature animated input text',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/form-wave',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/form-wave',
  },
  {
    name: 'Split Landing',
    description: 'Website template with feature landing page',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/split-landing',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/split-landing',
  },
  {
    name: 'Scroll Animation',
    description: 'Web component with feature scrolling animation effect',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/scroll-animation',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/scroll-animation',
  },
  {
    name: 'Blurry Loading',
    description: 'Web component with feature blurry page loading effect',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/blurry-loading',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/blurry-loading',
  },
  {
    name: 'Search Widget',
    description: 'Web component with feature hidden search widget',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/hidden-search',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/hidden-search',
  },
  {
    name: 'Rotating Navigation',
    description: 'Web component with feature rotating navigation animation',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/rotating-navigation',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/rotating-navigation',
  },
  {
    name: 'Progress Steps',
    description: 'Web component timeline with feature progress steps',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/progress-steps',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/progress-steps',
  },
  {
    name: 'Expanding Cards',
    description: 'Web component with feature expanding cards',
    tryItUrl: 'https://josephgattuso.github.io/50-projects/expanding-cards',
    repo: 'https://github.com/josephgattuso/50-projects/tree/master/expanding-cards',
  },
  ,
];
