export const projects = [
  {
    name: 'Monsters Rolodex',
    description: 'Building a contact directory app using React.',
    tryItUrl: 'https://josephgattuso.github.io/monsters-rolodex',
    repo: 'https://github.com/josephgattuso/monsters-rolodex',
  },
  {
    name: 'Calculator',
    description: 'Creating a simple calculator with plain JavaScript.',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/calculator',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/calculator',
  },
  {
    name: 'Quotes Generator',
    description: 'Using an API to build a random quote generator with Twitter integration.',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/quotes-generator',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/quotes-generator',
  },
  {
    name: 'Pokedex',
    description: 'Find info on Pokemon with this Pokedex app. Uses the Pokeapi.co API.',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/pokedex',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/pokedex',
  },
  {
    name: 'Hoverboard',
    description: 'Hoverboard app with color-change effect on mouse hover',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/hoverboard',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/hoverboard',
  },
  {
    name: 'Image Carousel',
    description: 'Web component with classic image carousel',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/image-carousel',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/image-carousel',
  },
  {
    name: 'Animated Countdown',
    description: 'Web compononet loader with feature animated countdown',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/animated-countdown',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/animated-countdown',
  },
  {
    name: 'Notes App',
    description: 'Create, Read, Edit, and Delete notes',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/notes-app',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/notes-app',
  },
  {
    name: 'Good Cheap Fast',
    description: 'Optimise your next project from a set of predifined criteria',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/good-cheap-fast',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/good-cheap-fast',
  },
  {
    name: 'Password Generator',
    description: 'Generate a random password with specific user settings',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/password-generator',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/password-generator',
  },
  {
    name: 'Auto Text Effect',
    description:
      'Web component with feature typing effect. Control speed using input field or keyboard arrows.',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/auto-text-effect',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/auto-text-effect',
  },

  {
    name: 'Hearts Click',
    description: 'Generate hearts at double-click events',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/double-heart-click',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/double-heart-click',
  },
  {
    name: 'Search Profiles',
    description: 'Search for any GitHub profile and returns key information.  Uses the GitHub API.',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/github-profiles',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/github-profiles',
  },
  {
    name: 'Toast Notifications',
    description: 'Generate toast notifications',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/toast-notifications',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/toast-notifications',
  },
  {
    name: 'Vertical Slider',
    description: 'Image carousel with sliding double vertical panels',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/double-vertical-slider',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/double-vertical-slider',
  },
  {
    name: 'Sticky Navigation',
    description: 'Website template with feature sticky navigation',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/sticky-navigation',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/sticky-navigation',
  },
  {
    name: 'Content Placeholder',
    description: 'Content placeholder component',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/content-placeholder',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/content-placeholder',
  },
  {
    name: 'Kinetic Loader',
    description: 'Kinetic page loading component',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/kinetic-loader',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/kinetic-loader',
  },
  {
    name: 'Drawing App',
    description: 'Drawing app using HTML canvas',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/drawing-app',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/drawing-app',
  },
  {
    name: "Drag 'N' Drop",
    description: 'Drag and drop component',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/drag-n-drop',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/drag-n-drop',
  },
  {
    name: 'Button Ripple',
    description: 'Button ripple effect',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/button-ripple',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/button-ripple',
  },
  {
    name: 'Theme Clock',
    description: 'Theme clock with feature dark mode toggle',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/theme-clock',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/theme-clock',
  },
  {
    name: 'Background Slider',
    description: 'Background slider project',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/background-slider',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/background-slider',
  },

  {
    name: 'Movie App',
    description: 'Search for movies and view movie info and ratings. Uses the moviedb API',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/movie-app',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/movie-app',
  },
  {
    name: 'Drink Water',
    description: 'Track your water intake with this handy water tracking app',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/drink-water',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/drink-water',
  },
  {
    name: 'Incrementing Counter',
    description: 'Incrementing counter widget',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/incrementing-counter',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/incrementing-counter',
  },
  {
    name: 'Animated Navigation',
    description: 'Website template with feature animated expanding navigation',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/animated-navigation',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/animated-navigation',
  },
  {
    name: 'Random Picker',
    description: 'Enter all of the choices divided by commas. Then press enter when you are done.',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/random-choice-picker',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/random-choice-picker',
  },
  {
    name: 'FAQ Collapse',
    description: 'Frequently asked questions',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/faq-collapse',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/faq-collapse',
  },
  {
    name: 'Event Keycodes',
    description: 'Press any key to get the keycode',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/event-keycodes',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/event-keycodes',
  },

  {
    name: 'Sound Board',
    description: 'Handy sound effects board',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/sound-board',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/sound-board',
  },
  {
    name: 'Form Wave',
    description: 'Login form with feature animated input text',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/form-wave',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/form-wave',
  },
  {
    name: 'Split Landing',
    description: 'Website template with feature landing page',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/split-landing',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/split-landing',
  },
  {
    name: 'Scroll Animation',
    description: 'Web component with feature scrolling animation effect',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/scroll-animation',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/scroll-animation',
  },
  {
    name: 'Blurry Loading',
    description: 'Web component with feature blurry page loading effect',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/blurry-loading',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/blurry-loading',
  },
  {
    name: 'Search Widget',
    description: 'Web component with feature hidden search widget',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/hidden-search',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/hidden-search',
  },
  {
    name: 'Rotating Navigation',
    description: 'Web component with feature rotating navigation animation',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/rotating-navigation',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/rotating-navigation',
  },
  {
    name: 'Progress Steps',
    description: 'Web component timeline with feature progress steps',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/progress-steps',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/progress-steps',
  },
  {
    name: 'Expanding Cards',
    description: 'Web component with feature expanding cards',
    tryItUrl: 'https://josephgattuso.github.io/js-projects/expanding-cards',
    repo: 'https://github.com/josephgattuso/js-projects/tree/master/expanding-cards',
  },
  ,
];
